fix for exception
TypeError: to_bytes() missing required argument 'length' (pos 1)

Test: atest HidHostTest
Flag: TEST_ONLY
Bug: 368575445
Change-Id: Ib368d61875c1ebf6c4aafddc2da7be23743c945b